FROM resin/rpi-raspbian:latest
RUN apt-get -y update
RUN apt-get -y install \
	gcc \
	build-essential \
	wget \
	make

#packet forwarder for imst iC880A
WORKDIR /opt

##  driver / hardware abstraction layer source
RUN wget https://github.com/Lora-net/lora_gateway/archive/v4.1.1.tar.gz
RUN tar zxf v4.1.1.tar.gz
## the packet_forwarder source
RUN wget https://github.com/Lora-net/packet_forwarder/archive/v3.1.0.tar.gz
RUN tar zxf v3.1.0.tar.gz

## repo with systemd rule
RUN wget https://github.com/dejwoo/packet_forwarder-scripts/archive/v0.3.tar.gz
RUN tar zxf v0.3.tar.gz
RUN ["mv","lora_gateway-4.1.1", "lora_gateway"]
RUN ["mv","packet_forwarder-3.1.0", "packet_forwarder"]
WORKDIR /opt/packet_forwarder-scripts-0.3
RUN chmod u+x ./set_config.sh
RUN chmod u+x ./reset.sh



## build driver/HAL
WORKDIR /opt/lora_gateway
RUN make all

## build packet_forwarder
WORKDIR /opt/packet_forwarder

RUN make all
## set enviroment variables
# 44454641554c5430 -> DEFAULT0
#TODO presunut do gateway.yml
# ENV PACKET_FORWARDER_GATEWAY_ID=44454641554c5430
# ENV PACKET_FORWARDER_SERVER_ADDRESS=localhost
# ENV PACKET_FORWARDER_SERV_PORT_UP=1680
# ENV PACKET_FORWARDER_SERV_PORT_DOWN=1680
# ENV PACKET_FORWARDER_KEEPALIVE_INTERVAL=10
# ENV PACKET_FORWARDER_STAT_INTERVAL=30
# ENV PACKET_FORWARDER_PUSH_TIMEOUT_MS=100
# ENV PACKET_FORWARDER_FORWARD_CRC_VALID=true
# ENV PACKET_FORWARDER_FORWARD_CRC_ERROR=false
# ENV PACKET_FORWARDER_FORWARD_CRC_DISABLED=false

WORKDIR /opt/packet_forwarder/lora_pkt_fwd/
RUN cp /opt/packet_forwarder-scripts-0.3/set_config.sh /opt/packet_forwarder-scripts-0.3/reset.sh /opt/packet_forwarder/lora_pkt_fwd/
RUN ["rm","-fv", "local_conf.json"]
RUN chmod u+x reset.sh
RUN chmod u+x set_config.sh
CMD ./set_config.sh && ./lora_pkt_fwd

